sampling:
  - layer: 1
    neighbor: 
      - 10
    strategy: 'recent'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 8
memory: 
  - type: 'node'
    dim_time: 100
    deliver_to: 'self'
    mail_combine: 'last'
    memory_update: 'gru'
    mailbox_size: 1
    combine_node_feature: True
    dim_out: 100
gnn:
  - arch: 'transformer_attention'
    layer: 2
    att_head: 2
    dim_time: 100
    dim_out: 100
    emb_reuse: True
train:
  - epoch: 10
    batch_size: 2000
    lr: 0.0001
    dropout: 0.2
    att_dropout: 0.2
    interval_to_gpu: True
    pre_load: True
