sampling:
  - layer: 2
    neighbor: 
      - 10
      - 10
    strategy: 'recent'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 8
memory: 
  - type: 'none'
    dim_out: 0
    mailbox_size: 0
gnn:
  - arch: 'transformer_attention'
    layer: 2
    att_head: 2
    dim_time: 100
    dim_out: 100
train:
  - epoch: 15
    batch_size: 2000
    lr: 0.0001
    dropout: 0.1
    att_dropout: 0.1
    interval_to_gpu: True
    pre_load: True
